from fastapi import APIRouter

from src.api import routes_candles, routes_meta, routes_tasks, routes_status, routes_watchlist, routes_realtime, routes_index, routes_concepts, routes_evaluations, routes_klines, routes_admin, routes_simulated, routes_earnings, routes_sectors, routes_concept_monitor_v2, routes_tonghuashun, routes_news, routes_us_stock, routes_screener, routes_rotation, routes_pattern, routes_sentiment, routes_anomaly, routes_crypto

api_router = APIRouter()

api_router.include_router(routes_meta.router, prefix="/symbols", tags=["symbols"])
api_router.include_router(routes_candles.router, prefix="/candles", tags=["candles"])
api_router.include_router(routes_tasks.router, prefix="/tasks", tags=["tasks"])
api_router.include_router(routes_status.router, prefix="/status", tags=["status"])
api_router.include_router(routes_watchlist.router, prefix="/watchlist", tags=["watchlist"])
api_router.include_router(routes_realtime.router, prefix="/realtime", tags=["realtime"])
api_router.include_router(routes_index.router, prefix="/index", tags=["index"])
api_router.include_router(routes_concepts.router, prefix="/concepts", tags=["concepts"])
api_router.include_router(routes_evaluations.router, prefix="/evaluations", tags=["evaluations"])
api_router.include_router(routes_klines.router, prefix="/klines", tags=["klines"])
api_router.include_router(routes_admin.router, prefix="/admin", tags=["admin"])
api_router.include_router(routes_simulated.router, prefix="/simulated", tags=["simulated"])
api_router.include_router(routes_earnings.router, prefix="/earnings", tags=["earnings"])
api_router.include_router(routes_sectors.router, prefix="/sectors", tags=["sectors"])
api_router.include_router(routes_concept_monitor_v2.router, prefix="/concept-monitor", tags=["concept-monitor"])
api_router.include_router(routes_tonghuashun.router)
api_router.include_router(routes_news.router, prefix="/news", tags=["news"])
api_router.include_router(routes_us_stock.router, prefix="/us-stock", tags=["us-stock"])
api_router.include_router(routes_crypto.router, prefix="/crypto", tags=["crypto"])
api_router.include_router(routes_screener.router)
api_router.include_router(routes_rotation.router)
api_router.include_router(routes_pattern.router)
api_router.include_router(routes_sentiment.router)
api_router.include_router(routes_anomaly.router)
